---
title: "Untitled"
author: "u7151703"
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#t10

```{r}
library(tidyverse)
library(readxl)
library(patchwork)
```

```{r}
c3t10r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t10r05k/sum_result.csv", show_col_types = FALSE)
View(c3t10r05k)
lnl_data <- c3t10r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-83250,-83240)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#t25

```{r}
c3t25r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t25r05k/sum_result.csv", show_col_types = FALSE)
View(c3t25r05k)
lnl_data <- c3t25r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-238200,-238140)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

# t50

```{r}
c3t50r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t50r05k/sum_result.csv", show_col_types = FALSE)
View(c3t50r05k)
lnl_data <- c3t50r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data %>% filter(method == 0), aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-465330,-465300)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

# t100

```{r}
c3t100r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t100r05k/sum_result.csv", show_col_types = FALSE)
View(c3t100r05k)
lnl_data <- c3t100r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-1000000,-997500)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```



# c6 t10

```{r}
c6t10r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t10r05k/sum_result.csv", show_col_types = FALSE)
View(c6t10r05k)
lnl_data <- c6t10r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data %>% filter(method == 5), aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(3,7)+
  ylim(-168990,-168960)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

# c6 t25

```{r}
c6t25r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t25r05k/sum_result.csv", show_col_types = FALSE)
View(c6t25r05k)
lnl_data <- c6t25r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data %>% filter(method == 4 | method == 3 | method == 2), aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(5,7)+
  ylim(-475810,-475800)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

# c6 t50

```{r}
c6t50r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t50r05k/sum_result.csv", show_col_types = FALSE)
View(c6t50r05k)
lnl_data <- c6t50r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data %>% filter(method == 2 | method == 4), aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(5,7)+
  ylim(-923560,-923510)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#c6 t100

```{r}
c6t100r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t100r05k/sum_result.csv", show_col_types = FALSE)
View(c6t100r05k)
lnl_data <- c6t100r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(4,7)+
  ylim(-1974000,-1970000)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#draft

```{r}
c3t10r05k <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t10r05k/sum_result.csv", show_col_types = FALSE)
View(c3t10r05k)
lnl_data <- c3t10r05k
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-83250,-83240)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```
