---
title: "Untitled"
author: "u7151703"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

#t50

```{r}
c3t50r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t50r0/sum_result.csv", show_col_types = FALSE)
View(c3t50r0)
lnl_data <- c3t50r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-93850,-93800)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```



```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```


#t100

```{r}
c3t100r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t100r0/sum_result.csv", show_col_types = FALSE)
View(c3t100r0)
lnl_data <- c3t100r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data , aes(x = as.character(class), y = lnl, color = as.character(method)))+
  geom_jitter(width = 0.25)+
  #xlim(2,4)+
  ylim(-200900,-200600)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```


#t25

```{r}
c3t25r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t25r0/sum_result.csv", show_col_types = FALSE)
View(c3t25r0)
lnl_data <- c3t25r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data %>% filter(class > 1), aes(x =  as.character(class), y = lnl, color = as.character(method)))+
  geom_jitter(width = 0.25)+
  #xlim(2,4)+
  ylim(-47710,-47700)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#t10

```{r}
c3t10r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c3t10r0/sum_result.csv", show_col_types = FALSE)
View(c3t10r0)
lnl_data <- c3t10r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(2,4)+
  ylim(-16780,-16770)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method < 3) %>% filter(class == 3) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 0 ~ "0_c3",
    method == 1 ~ "1_c3",
    method == 2 ~ "2_c3"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

# PCA

```{r}
f81c3_para <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/data/pca_candi/c31k/para.xlsx")
```

```{r}
para_sub <- f81c3_para

pca1 <- prcomp(para_sub[,c(10:13)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 3)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p1
```



#c6 t100

```{r}
c6t100r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t100r0/sum_result.csv", show_col_types = FALSE)
View(c6t100r0)
lnl_data <- c6t100r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(5,7)+
  ylim(-395600,-395500)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method == 1 | method == 2) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 1 ~ "1_c6",
    method == 2 ~ "2_c6"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#c6 t50

```{r}
c6t50r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t50r0/sum_result.csv", show_col_types = FALSE)
View(c6t50r0)
lnl_data <- c6t50r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(5,7)+
  ylim(-185000,-184950)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method == 1 | method == 2) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 1 ~ "1_c6",
    method == 2 ~ "2_c6"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#c6 t25

```{r}
c6t25r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t25r0/sum_result.csv", show_col_types = FALSE)
View(c6t25r0)
lnl_data <- c6t25r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(4,7)+
  ylim(-94785,-94750)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method == 1 | method == 2) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 1 ~ "1_c6",
    method == 2 ~ "2_c6"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

#c6 t10

```{r}
c6t10r0 <- read_csv("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t10r0/sum_result.csv", show_col_types = FALSE)
View(c6t10r0)
lnl_data <- c6t10r0
```


```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
ggplot(lnl_data, aes(x = class, y = lnl, color = as.character(method)))+
  geom_point()+
  xlim(3,7)+
  ylim(-33570,-33555)+
  geom_line(aes(group = rep))+
  theme_bw()
```

```{r}
times <- lnl_data %>%
  group_by(rep) %>%
  summarize(runtime = sum(time)) %>%
  left_join(lnl_data %>%
              distinct(rep, method),
            by = "rep") %>%
  select(rep, runtime, method)

temptime <- lnl_data %>% filter(method == 1 | method == 2) %>% filter(class == 6) %>%
  mutate(runtime = time) %>%
  select(rep, runtime, method) %>%
  mutate(method = case_when(
    method == 1 ~ "1_c6",
    method == 2 ~ "2_c6"
  ))

times <- rbind(times, temptime)
```

```{r}
ggplot(times, aes(x = as.character(method), y = runtime, color = method))+
  geom_boxplot()+
  labs(y = 'runtime(s)')+
  theme_bw()
```

```{r}
lrt_results <- lnl_data %>%
  group_by(rep) %>%
  summarize(lrt_detail = paste(lrt, collapse = "_"))

table(lrt_results)
```

```{r}
f81c6_para <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/data/pca_candi/c61k/para.xlsx")
```

```{r}
para_sub <- f81c6_para

pca1 <- prcomp(para_sub[,c(10:13)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 3)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p1
```

