---
title: "Untitled"
author: "u7151703"
date: "2024-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(patchwork)
library(readxl)
options(scipen=999)
```

# method test
```{r}
c6t50r05k_para <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/data/f81_qmix/c6t50r05k/para.xlsx")
```

```{r}
para_sub <- c6t50r05k_para

para_sub <- para_sub %>%
  separate(name, into = c("dataset", "method", "rep", "nclass"), sep = "_")
para_sub$name <- c6t50r05k_para$name
para_sub <- para_sub %>% select(name, everything())
```

```{r}
pca1 <- prcomp(para_sub[,c(15:18)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")

df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class
df1$method <- para_sub$method
df1$nclass <- para_sub$nclass
df1$rep <- para_sub$rep
```

```{r}
p1 = ggplot(data = df1 %>% filter(method == 'i3') ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  #scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,nrow = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p1
```

```{r}
p2 = ggplot(data = df1 %>% filter(nclass %in% c('c6init', 'c6') 
                                  & method %in% c('i3', 'i4','i5')
                                  & rep == 'r1') ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  #scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,nrow = 3)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p2
```

```{r}
class_sub <- para_sub %>% filter(class == 1 & method == 'i3' & nclass == 'c5')
list(class_sub$lnl)
```



# turtle
```{r}
turtlet1 <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/data/turtle/t1/para.xlsx")
turtlet5 <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/data/turtle/t5/para.xlsx")
```



```{r}
para_sub <- turtlet1

para_sub$qAC_l <- log(para_sub$qAC,base = 10)
para_sub$qAG_l <- log(para_sub$qAG,base = 10)
para_sub$qAT_l <- log(para_sub$qAT,base = 10)
para_sub$qCG_l <- log(para_sub$qCG,base = 10)
para_sub$qCT_l <- log(para_sub$qCT,base = 10)
para_sub$qGT_l <- log(para_sub$qGT,base = 10)

pca1 <- prcomp(para_sub[,c(21:26)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  #scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()

p1
```

```{r}
p12 = ggplot(data = df1 %>% filter(name %in% c('turtle_t1_c1_r3','turtle_t1_c2_r1')) ,aes(x = PC1,y = PC2, color = name))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(5, 10)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(color = "none", size = "none")+
  theme_bw()

p12
```

```{r}
p23 = ggplot(data = df1 %>% filter(name %in% c('turtle_t1_c2_r1','turtle_t1_c3_r4')) ,aes(x = PC1,y = PC2, color = name))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(5, 10)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(color = "none", size = "none")+
  theme_bw()

p23
```

```{r}
p34 = ggplot(data = df1 %>% filter(name %in% c('turtle_t1_c3_r4','turtle_t1_c4_r3')) ,aes(x = PC1,y = PC2, color = name))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(5, 10)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(color = "none", size = "none")+
  theme_bw()

p34
```

```{r}
p45 = ggplot(data = df1 %>% filter(name %in% c('turtle_t1_c4_r3','turtle_t1_c5_r1')) ,aes(x = PC1,y = PC2, color = name))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(5, 10)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(color = "none", size = "none")+
  theme_bw()

p45
```

```{r}
p56 = ggplot(data = df1 %>% filter(name %in% c('turtle_t1_c5_r1','turtle_t1_c6_r3')) ,aes(x = PC1,y = PC2, color = name))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(5, 10)) +
  labs(x = xlab1,y = ylab1, size = "weight")+
  guides(color = "none", size = "none")+
  theme_bw()

p56
```

```{r}
(p12 | p23) / (p34 | p45) / (p56 | p56)
```


# underfitting
```{r}
c3_dq7_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c3_dq7/para.xlsx")
```

```{r}
para_sub <- c3_dq7_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$data <- para_sub$data
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-1.5,0)+
  #ylim(-1.5,1)+
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~data,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  ggtitle("data 1") + theme(plot.title = element_text(hjust = 0.5))

p1
```

# overfitting
```{r}
c5_dq3_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c5_dq3/para.xlsx")
```

```{r}
para_sub <- c5_dq3_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$data <- para_sub$data
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-1.5,0)+
  #ylim(-1.5,1)+
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~data,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  ggtitle("data 1") + theme(plot.title = element_text(hjust = 0.5))

p1
```

# c3 to q3
```{r}
c3_dq3_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c3_dq3/para.xlsx")
```

```{r}
para_sub <- c3_dq3_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class_ind <- para_sub$class_ind
df1$optimiser <- para_sub$optimiser

p1 = ggplot(data = df1 %>% filter(optimiser != 'bfgs'),aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-1.5,0)+
  #ylim(-1.5,1)+
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+ theme(plot.title = element_text(hjust = 0.5))

p1
```

# c3 to s3
```{r}
c3_ds3_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c3_ds3/para.xlsx")
```

```{r}
para_sub <- c3_ds3_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$data <- para_sub$data
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-1.5,0)+
  #ylim(-1.5,1)+
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~data,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  ggtitle("data 1") + theme(plot.title = element_text(hjust = 0.5))

p1
```

# 1 to 7

```{r}
c17_dq7_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c1-7_dq7/para.xlsx")
```

```{r}
para_sub <- c17_dq7_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 %>% filter(name %in% c('q1_bfgs0_dq7_rep1','q2_bfgs0_dq7_rep1','q3_bfgs0_dq3_rep2','q4_bfgs0_dq7_rep3','q5_bfgs0_dq7_rep2','q6_bfgs0_dq7_rep3','q7_bfgs0_dq7_rep1','sim_q7')) ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-12,5.0)+
  #ylim(0.5,1.5)+
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 4)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p1
```


```{r}
para_sub <- c17_dq7_data[c(31:147),]

pca2 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df2 <- pca2$x 
df2 <- as.data.frame(df2) 

summ2 <- summary(pca2)
xlab2 <- paste0("PC1(",round(summ2$importance[2,1]*100,2),"%)")
ylab2 <- paste0("PC2(",round(summ2$importance[2,2]*100,2),"%)")
```

```{r}
df2$name <- para_sub$name
df2$weight <- para_sub$weight
df2$class <- para_sub$class

p2 = ggplot(data = df2 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  #xlim(-2.5,5.0)+
  #ylim(0.5,1.5)+
  labs(x = xlab2,y = ylab2,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p2
```


```{r}
c3_dq3_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c3_dq3/para.xlsx")
```

```{r}
para_sub <- c3_dq3_data

pca1 <- prcomp(para_sub[,c(14:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p1
```

```{r}
c3_df3_data <- read_excel("C:/Users/u7151703/Desktop/research/optimisation/c3_df3/para.xlsx")
```

```{r}
para_sub <- c3_df3_data

pca1 <- prcomp(para_sub[,c(16:19)],center = FALSE, scale. = FALSE)

df1 <- pca1$x 
df1 <- as.data.frame(df1) 

summ1 <- summary(pca1)
xlab1 <- paste0("PC1(",round(summ1$importance[2,1]*100,2),"%)")
ylab1 <- paste0("PC2(",round(summ1$importance[2,2]*100,2),"%)")
```

```{r}
df1$name <- para_sub$name
df1$weight <- para_sub$weight
df1$class <- para_sub$class

p1 = ggplot(data = df1 ,aes(x = PC1,y = PC2))+
  geom_point(aes(size = weight), alpha = 0.2)+
  scale_size_continuous(range = c(1, 5)) +
  labs(x = xlab1,y = ylab1,color = "sample data", size = "weight")+
  guides(fill = "none")+
  facet_wrap(~name,ncol = 5)+
  #geom_text(aes(label = class), vjust = 1.5, size = 3.5)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))

p1
```



